package com.example.onetaptransit.consts

const val STATIC_ZIP_FILENAME = "staticData.zip"
const val REALTIME_PB_FILENAME = "realtimeData.pb"

const val KEY_STATIC_TABLE_NAME = "KEY_STATIC_TABLE_NAME"

const val STATIC_DATA_IMPORT_UNIQUE_WORK_NAME = "STATIC_DATA_IMPORT_UNIQUE_WORK_NAME"
const val STATIC_DATA_TABLE_IMPORTER_TAG = "STATIC_DATA_TABLE_IMPORTER_TAG"
const val WORKER_PROGRESS = "WORKER_PROGRESS"